### ISSUE TITLE
Parse error in open-sir CLI using Windows cmd  command line

### ISSUE THREAD

**Issue by felipehuerta17** [open-sir/open-sir#30]
A good amount of Python users who use Windows as their operating system have Python installed using Anaconda. By default, the Anaconda Prompt is a cmd shell and most python commands are run in the conda environment embedded in a cmd shell.

When trying to use the open-sir CLI in windows cmd

`pipenv run python open-sir.py -p '[0.95,0.38]' -i '[341555,445,0]' -t 6`

An error is obtained
```
Traceback (most recent call last):
  File "open-sir.py", line 39, in <module>
    run_cli()
  File "open-sir.py", line 35, in run_cli
    sol.set_params(p, w0).solve(**kwargs).export(sys.stdout)
  File "C:\open-sir\models\sir.py", line 60, in set_params
    self._set_params(p, initial_conds)
  File "C:\open-sir\models\model.py", line 54, in _set_params
    if len(p) != num_params or len(initial_conds) != num_ic:
TypeError: len() of unsized object
```

@jia200x thinks that this is caused because of not making the CLI full POSIX.

I haven't tried this in Powershell, but the issue is persistent on cmd.

**Comment by felipehuerta17** [comment]
Hi all,

I tried the above on anaconda prompt in Powershell with my new laptop and works fine. It is something related to windows cmd.

**Comment by jia200x** [comment]
I think this happens because of the ugly input format for the parameters. That's absolutely not portable.

Maybe we should think of an input file?

**Comment by sasalatart** [comment]
@jia200x  If that is the case, I think we should support both options. If no parameters are found, then assume it is in a file, or something like that?

**Comment by felipehuerta17** [comment]
@gwenzel had an installation issue with pipenv. 

For some reason his local version added a package python==3.7 and that raised an installation error. We should keep an eye on it.

**Comment by jia200x** [comment]
> @jia200x If that is the case, I think we should support both options. If no parameters are found, then assume it is in a file, or something like that?
I read this comment a little bit late, sorry :(

I'm using for now an "input param" file that can be read from STDIN or a CLI param (see #34 ).
If we need to add these params to the CLI args (as @sasalatart proposes), we can indeed do it.

**Comment by jia200x** [comment]
@felipehuerta17 is this issue still present?

**Comment by felipehuerta17** [comment]
@jia200x made an excellent improvement on #34. 

However, I just realized that our CLI [documentation](https://open-sir.readthedocs.io/en/latest/doc/getting-started.html) has a small error.

It is not immediately obvious that 
```
usage: opensir-cli [-h] [-m {sir,sirx}] [-t TIME] [-f FILE] [-s] [-d DELIMITER] 
```

Has to be prefixed by python if it's intended to be run from a CLI.

In the example below,

```
opensir-cli --model sir --time 6 --file input_file.txt
```

Will not run unless it is called from a Jupyter Notebook or from a python shell.  My suggestion is to update the documentation.

**Comment by jia200x** [comment]
> Has to be prefixed by python if it's intended to be run from a CLI.

It shouldn't be prefixed with a `python` command. The CLI is an executable file with a proper python [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix))

> Will not run (at least in Win10) unless it is called from a Jupyter Notebook or from a python shell.

Did you install the package using `pip`? 

In theory one should be able to do this:
```
pip install .
open-sir-cli --help
```

If this is not working under Windows, there's something wrong with the setuptools package and IMO we should fix that instead of updating the documentation. Calling an executable without the `python` prefix is intended

**Comment by jia200x** [comment]
(I'm 100% sure python executables are compatible with Windows. If this is not working, maybe I did something wrong with the package)

**Comment by felipehuerta17** [comment]
@jia200x doesn't work in Powershell

![image](https://user-images.githubusercontent.com/33637198/79694310-7090c680-8267-11ea-8c6b-c5934e9bdf8f.png)

![image](https://user-images.githubusercontent.com/33637198/79694317-7dadb580-8267-11ea-832a-08f1c0aaebb0.png)

**Comment by jia200x** [comment]
hmmm there might be something wrong with the deployment setup. I will give it a look.

Thanks for testing!
